jobs:
  job1:
    requires: [ ~pr, ~commit ]
    image: node:16
    steps:
      - main: echo hoge
  job2:
    annotations:
      screwdriver.cd/jobDisabledByDefault: true
    requires: [ ~pr, ~commit ]
    image: node:16
    steps:
      - main: echo hoge

